# Generated by Django 4.1.3 on 2022-12-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', models.CharField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес записи')),
            ],
        ),
    ]
