# Generated by Django 4.1.3 on 2022-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_fm_image_fm_image1_fm_image2_fm_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
