# Generated by Django 4.1.3 on 2022-12-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fm_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='image5',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото 5'),
        ),
    ]
