# Generated by Django 4.1.3 on 2022-12-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fm_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=models.CharField(max_length=1500, verbose_name='Описание'),
        ),
    ]
