# Generated by Django 4.1.3 on 2022-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_fm_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='is_pub',
            field=models.BooleanField(default=False),
        ),
    ]
