# Generated by Django 4.1.3 on 2022-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fm_is_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
