# Generated by Django 4.1.3 on 2022-12-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_fm_is_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=models.CharField(max_length=1200, verbose_name='Описание'),
        ),
    ]
