# Generated by Django 4.1.3 on 2022-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_fm_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fm',
            options={'verbose_name_plural': 'Model'},
        ),
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=models.CharField(max_length=1200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='image1',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Photo 1'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='image3',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Photo 3'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='image4',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Photo 4'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='image5',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Photo 5'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
