# Generated by Django 4.1.3 on 2022-12-16 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_fm_options_alter_fm_desc_alter_fm_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='images_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
