# Generated by Django 4.1.3 on 2022-12-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_fm_images_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fm',
            name='images_count',
        ),
        migrations.AddField(
            model_name='fm',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
