# Generated by Django 4.1.3 on 2022-12-17 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_fm_images_count_fm_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Д'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fm',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='O'),
        ),
    ]
