# Generated by Django 4.1.3 on 2022-12-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_fm_added_fm_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
    ]
