# Generated by Django 4.1.3 on 2022-12-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_fm_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='vac',
            field=models.CharField(blank=True, max_length=740, verbose_name='Vacancy'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
