# Generated by Django 4.1.3 on 2022-12-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_fm_vac_alter_fm_added_alter_fm_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='is_vac',
            field=models.BooleanField(default=False, verbose_name='Is Vacancy'),
        ),
    ]
