# Generated by Django 4.1.3 on 2022-12-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_fm_is_vac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=models.CharField(blank=True, max_length=740, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
