# Generated by Django 4.1.3 on 2022-12-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_fm_image_vac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fm',
            name='vac',
        ),
    ]
