# Generated by Django 4.1.3 on 2022-12-17 04:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_fm_vac'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm',
            name='vac',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
