# Generated by Django 4.1.4 on 2022-12-17 04:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_fm_vac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='vac',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True),
        ),
    ]
