# Generated by Django 4.1.4 on 2022-12-17 04:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_fm_vac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='vac',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
