# Generated by Django 4.1.3 on 2022-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_vacancy_image_vac_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='image_vac_post',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Вакансия сверху'),
        ),
    ]
