# Generated by Django 4.1.3 on 2022-12-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_vacancy_image_vac_post_vacancy_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image_vac',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Photo Vacancy (3:1)'),
        ),
    ]
