# Generated by Django 4.1.3 on 2022-12-17 11:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_vacancy_image_vac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='At the top of the page'),
        ),
    ]
